---
- name: This is a hello-world example
  hosts: localhost 
  tasks:
    - name: Print Hello
      action: command echo "Hello World"
      register: hello 

    - debug: msg="{{ hello.stdout }}"

    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
      copy:
        content: hello world
        dest: //home/ec2-user/syed/testfile.txt
