---
 - debug: msg="{{ sub_add_item.1[1:] }}" 
 - name: Get Subscription Id.
   uri:
     url: "{{ st_api_url }}/subscriptions?account={{ accountname }}&folder=%2F{{ sub_add_item.1[1:]  }}"
     method: GET
     body: "{{ accountname }}"
     body_format: json
     user: admin
     password: admin
     force_basic_auth: yes
     validate_certs: no
     return_content: yes
     status_code: '200,204'
   register: json_resp_get_sub_id

 - debug: msg="json_resp_get_sub_id {{ json_resp_get_sub_id.json }}" 
   

 - set_fact:
      dict1: 
         subscriptions: 
                 - '{{ json_resp_get_sub_id.json.subscriptions[0].id }}'
   when: sub_add_item.0 == 0

 - set_fact:
      dict1: 
         subscriptions: "{{ dict.subscriptions }} + [ '{{  json_resp_get_sub_id.json.subscriptions[0].id }}' ]"
   when: sub_add_item.0 > 0
   
 - debug: msg="dict1 {{ dict1 }}"
