---
 - set_fact:
      accountname: "{{ accountname }}"
      st_api_url: "https://{{ hostname }}:8444/api/v1.4"
      
 - set_fact:
      src_account_json: "accounts/{{ accountname }}/{{ accountname }}_account.json"
  
 - set_fact:
      st_account_url: "{{ st_api_url }}/accounts"
      account_version_file: "{{ lookup('file' , '{{ src_account_json }}') | from_json }}"
  
 - debug: msg="st_account_url {{ st_account_url }}"
 - debug: msg="account_version_file {{ account_version_file }}"
 - name: Create/Update an Account. 
   uri:
      url: "{{ st_account_url }}"
      method: POST 
      body: "{{ account_version_file }}"
      body_format: json
      user: admin
      password: admin              
      force_basic_auth: yes
      validate_certs: no
      return_content: yes
      status_code: '204'
   register: post_account_resp
 - debug: msg="post_account_resp {{ post_account_resp }}"
