---
 - debug: msg="simple_item_create_update {{ simple_item_create_update }}"
 - debug: msg="simple_item_create_update.steps {{ simple_item_create_update.routesteps }}"

 - name: Create Simple Routes
   uri:
      url: "{{ st_api_url }}/routes"
      method: POST
      body: "{{ simple_item_create_update.route }}"
      body_format: json
      user: admin
      password: admin
      force_basic_auth: yes
      validate_certs: no
      return_content: yes
      status_code: '204,201'
   register: json_resp_simpl_route_create
   when: simple_item_create_update.route.name == "{{ simp_route_name }}"
   
 - set_fact:
      stepconfig:
              type: 'ExecuteRoute'
              status: 'ENABLED'
              autostart: false
              executeRoute: "{{ json_resp_simpl_route_create.json.id }}"
   when: simple_item_create_update.route.name == "{{ simp_route_name }}"              

 - name: Add execute Route for tagging comp and simple route.
   uri:
      url: "{{ st_api_url }}/routes/{{ compid }}/steps"
      method: POST
      body: "{{ stepconfig }}"
      body_format: json
      user: admin
      password: admin
      force_basic_auth: yes
      validate_certs: no
      return_content: yes
      status_code: '204,201'
   register: json_resp_simpl_route_tag
   when: simple_item_create_update.route.name == "{{ simp_route_name }}"

 - name: Create/Update Route Steps.
   uri:
      url: "{{ st_api_url }}/routes/{{ json_resp_simpl_route_create.json.id }}/steps"
      method: PUT
      body: "{{ simple_item.routesteps }}"
      body_format: json
      user: admin
      password: admin
      force_basic_auth: yes
      validate_certs: no
      return_content: yes
      status_code: '204,200'
   register: json_resp_simpl_route_steps
   when: simple_item_create_update.route.name == "{{ simp_route_name }}"
